import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import leadsRouter from "./leads";
import customersRouter from "./customers";
import propertiesRouter from "./properties";
import servicesRouter from "./services";
import quotesRouter from "./quotes";
import jobsRouter from "./jobs";
import invoicesRouter from "./invoices";
import crewsRouter from "./crews";
import dashboardRouter from "./dashboard";
import contactsRouter from "./contacts";
import recurringPlansRouter from "./recurring_plans";
import tasksRouter from "./tasks";
import stripeRouter from "./stripe";
import automationsRouter from "./automations";
import adminRouter from "./admin";
import profileRouter from "./profile";
import activityLogsRouter from "./activity_logs";
import emailTemplatesRouter from "./email_templates";
import emailsRouter from "./emails";
import campaignsRouter from "./campaigns";
import storageRouter from "./storage";
import attachmentsRouter from "./attachments";
import importBatchesRouter from "./import_batches";
import paymentsRouter from "./payments";
import customerCreditsRouter from "./customer-credits";
import financialReconciliationRouter from "./financial-reconciliation";
import financialApprovalsRouter from "./financial-approvals";
import automationEventsRouter from "./automation-events";
import communicationSafetyRouter from "./communication-safety";
import profileDetailsRouter from "./profile-details";
import estimatesRouter from "./estimates";
import calendarRouter from "./calendar";
import scheduleQueueRouter from "./schedule-queue";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(leadsRouter);
router.use(customersRouter);
router.use(propertiesRouter);
router.use(servicesRouter);
router.use(quotesRouter);
router.use(jobsRouter);
router.use(invoicesRouter);
router.use(crewsRouter);
router.use(dashboardRouter);
router.use(contactsRouter);
router.use(recurringPlansRouter);
router.use(tasksRouter);
router.use(stripeRouter);
router.use(automationsRouter);
router.use(adminRouter);
router.use(profileRouter);
router.use(activityLogsRouter);
router.use(emailTemplatesRouter);
router.use(emailsRouter);
router.use(campaignsRouter);
router.use(storageRouter);
router.use(attachmentsRouter);
router.use(importBatchesRouter);
router.use(paymentsRouter);
router.use(customerCreditsRouter);
router.use(financialReconciliationRouter);
router.use(financialApprovalsRouter);
router.use(automationEventsRouter);
router.use(communicationSafetyRouter);
router.use(profileDetailsRouter);
router.use(estimatesRouter);
router.use(calendarRouter);
router.use(scheduleQueueRouter);

export default router;
