// Zod schemas and all names unique to the generated api barrel
export * from "./generated/api";

// TypeScript types that are only in the types barrel (not duplicated by api barrel above).
// Explicit named re-exports resolve the TS2308 wildcard ambiguity.
export type {
  AuthorizationSessionHeaderParameter,
  AuthUser,
  AuthUserEnvelope,
  AutomationRule,
  AutomationRunResult,
  BeginBrowserLoginParams,
  Contact,
  Crew,
  Customer,
  DashboardStats,
  GeneratePaymentLink200,
  GenerateRecurringJob201,
  HealthStatus,
  Invoice,
  Job,
  JobCustomer,
  JobLinkedQuote,
  JobProperty,
  Lead,
  ListContactsParams,
  ListCustomersParams,
  ListInvoicesParams,
  ListJobsParams,
  ListLeadsParams,
  ListMessageLogsParams,
  ListPropertiesParams,
  ListQuotesParams,
  ListRecurringPlansParams,
  ListTasksParams,
  MessageLog,
  Property,
  Quote,
  QuoteCustomer,
  QuoteLineItem,
  QuoteLineItemInput,
  QuoteProperty,
  RecurringPlan,
  Service,
  Task,
} from "./generated/types";
